# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 265)
        Form.setAcceptDrops(True)
        self.generate_button = QtWidgets.QPushButton(Form)
        self.generate_button.setGeometry(QtCore.QRect(280, 200, 111, 41))
        self.generate_button.setObjectName("generate_button")
        self.code_box = QtWidgets.QLineEdit(Form)
        self.code_box.setGeometry(QtCore.QRect(80, 61, 511, 21))
        self.code_box.setObjectName("code_box")
        self.otp_box = QtWidgets.QLineEdit(Form)
        self.otp_box.setGeometry(QtCore.QRect(220, 125, 111, 31))
        self.otp_box.setObjectName("otp_box")
        self.copy_button = QtWidgets.QPushButton(Form)
        self.copy_button.setGeometry(QtCore.QRect(350, 125, 81, 28))
        self.copy_button.setObjectName("copy_button")
        self.close_button = QtWidgets.QPushButton(Form)
        self.close_button.setGeometry(QtCore.QRect(510, 205, 81, 31))
        self.close_button.setObjectName("close_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 65, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 135, 55, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "OTP Generate"))
        self.generate_button.setText(_translate("Form", "Generate"))
        self.copy_button.setText(_translate("Form", "Copy"))
        self.close_button.setText(_translate("Form", "Close"))
        self.label.setText(_translate("Form", "Code"))
        self.label_2.setText(_translate("Form", "OTP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
